export const API_ENDPOINTS = {
    REGISTER: '/users/register',
    LOGIN: '/users/login',
    GET_USER_PROFILE: '/users/profile/',
    CREATE_PORTFOLIO: '/portfolios',
    GET_PORTFOLIO: '/portfolios/',
    CREATE_COMMUNITY: '/communities',
    GET_COMMUNITY: '/communities/',
    CREATE_PROJECT: '/projects',
    GET_PROJECT: '/projects/',
    SUBMIT_FEEDBACK: '/feedback',
    GET_FEEDBACK: '/feedback/',
    CREATE_DISCUSSION: '/discussions',
    GET_DISCUSSIONS: '/discussions/',
    ADD_RESOURCE: '/resources',
    GET_RESOURCES: '/resources/',
    CREATE_AI_MENTOR: '/mentor',
    GET_AI_MENTOR: '/mentor/',
    AWARD_ACHIEVEMENT: '/achievements',
    GET_USER_ACHIEVEMENTS: '/achievements/',
    GET_LEADERBOARD: '/leaderboards/',
    GET_DASHBOARD: '/dashboard/',
};
